##########################################################################
# 部署配置文件(base)
# 本配置文件(xx.yml)中的变量(${xxx})是从同级目录下的.env文件中读取的
##########################################################################
# compose支持的版本2
version: "2"
services:
  # prometheus
  prometheus:
    image: ${IMAGE_PROMETHEUS}
    container_name: "prometheus.${PRODUCT_NAME}.${COMPANY_NAME}"
    hostname: "prometheus.${PRODUCT_NAME}.${COMPANY_NAME}"
    restart: "always"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./volume/prometheus/conf/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./volume/prometheus/conf/prometheus.rules.yml:/etc/prometheus/prometheus.rules.yml:ro
      - ./volume/prometheus/data:/prometheus:rw
      #- ./volume/prometheus/logs:/tmp:rw
    network_mode: "host"
  # grafana
  grafana:
    image: ${IMAGE_GRAFANA}
    container_name: "grafana.${PRODUCT_NAME}.${COMPANY_NAME}"
    hostname: "grafana.${PRODUCT_NAME}.${COMPANY_NAME}"
    restart: "always"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./volume/grafana/conf/grafana.ini:/etc/grafana/grafana.ini:ro
      - ./volume/grafana/data:/var/lib/grafana:rw
      - ./volume/grafana/logs:/var/log/grafana:rw
    network_mode: "host"
